data=[
  {
    "timestamp": "2026-07-09 10:15:22",
    "full_name": "Abel Tesfaye",
    "company_name": "Bright Future Academy",
    "email": "abel@brightfutureacademy.com",
    "phone": "+251911234567",
    "business_type": "Private school",
    "number_of_employees": "Around 40 staff members",
    "how_did_you_hear_about_us": "I found your website while searching for school management systems",
    "what_product_are_you_interested_in": "Student management and attendance software",
    "describe_your_current_problem": "We are still using paper attendance sheets and Excel files. It takes too much time to prepare reports and sometimes information gets lost.",
    "how_are_you_solving_this_problem_now": "Mostly manual work with Excel and notebooks",
    "what_is_your_main_goal": "We want to save time and have all student information in one place",
    "do_you_have_budget_for_this_solution": "Yes, we have allocated some budget for improving our school system",
    "estimated_budget": "Between 5000 and 10000 birr",
    "who_will_make_the_final_decision": "I am the school owner and I will make the decision",
    "when_are_you_planning_to_start": "Hopefully within the next one or two months before the new semester",
    "have_you_used_similar_products_before": "No",
    "additional_comments": "We would like to see a demo first before making a decision"
  },
  {
    "timestamp": "2026-07-09 11:42:10",
    "full_name": "Mekdes Alemayehu",
    "company_name": "Green Valley Coffee Export",
    "email": "mekdes@greenvalleycoffee.com",
    "phone": "+251922345678",
    "business_type": "Coffee export company",
    "number_of_employees": "About 70 employees",
    "how_did_you_hear_about_us": "LinkedIn post",
    "what_product_are_you_interested_in": "Business analytics dashboard",
    "describe_your_current_problem": "We have reports but they are not organized. It is difficult to see performance quickly.",
    "how_are_you_solving_this_problem_now": "Our employees prepare Excel reports every month",
    "what_is_your_main_goal": "Better understanding of sales and operations",
    "do_you_have_budget_for_this_solution": "We might have budget but need approval from management",
    "estimated_budget": "Not decided yet",
    "who_will_make_the_final_decision": "The general manager",
    "when_are_you_planning_to_start": "Maybe later this year",
    "have_you_used_similar_products_before": "No",
    "additional_comments": "Please send more information about pricing"
  },
  {
    "timestamp": "2026-07-09 13:05:44",
    "full_name": "Samuel Bekele",
    "company_name": "Nova Manufacturing",
    "email": "samuel@novamanufacturing.com",
    "phone": "+251933456789",
    "business_type": "Manufacturing",
    "number_of_employees": "More than 200",
    "how_did_you_hear_about_us": "Trade exhibition",
    "what_product_are_you_interested_in": "Inventory management system",
    "describe_your_current_problem": "Sometimes we don't know the exact stock available. It causes delays.",
    "how_are_you_solving_this_problem_now": "We have an old software but it is not working well",
    "what_is_your_main_goal": "Reduce mistakes and improve inventory tracking",
    "do_you_have_budget_for_this_solution": "I am not sure. I need to discuss with finance department",
    "estimated_budget": "Unknown",
    "who_will_make_the_final_decision": "The CEO and finance manager",
    "when_are_you_planning_to_start": "We are just researching options currently",
    "have_you_used_similar_products_before": "Yes, we use another system",
    "additional_comments": "Contact me again after I talk with my team"
  },
  {
    "timestamp": "2026-07-09 14:30:18",
    "full_name": "Liya Worku",
    "company_name": "Community Support Organization",
    "email": "liya@communitysupport.org",
    "phone": "+251944567890",
    "business_type": "NGO",
    "number_of_employees": "10-15 people",
    "how_did_you_hear_about_us": "Facebook advertisement",
    "what_product_are_you_interested_in": "Project management tool",
    "describe_your_current_problem": "We sometimes have communication problems between volunteers",
    "how_are_you_solving_this_problem_now": "We use Telegram and WhatsApp groups",
    "what_is_your_main_goal": "Make teamwork easier",
    "do_you_have_budget_for_this_solution": "Currently we don't have a budget",
    "estimated_budget": "No budget available",
    "who_will_make_the_final_decision": "The board members",
    "when_are_you_planning_to_start": "Not sure, maybe in the future",
    "have_you_used_similar_products_before": "No",
    "additional_comments": "I just wanted to learn more about the product"
  },
  {
    "timestamp": "2026-07-09 15:22:55",
    "full_name": "Daniel Worku",
    "company_name": "EthioTech Solutions",
    "email": "daniel@ethiotechsolutions.com",
    "phone": "+251955678901",
    "business_type": "Software company",
    "number_of_employees": "Around 100 employees",
    "how_did_you_hear_about_us": "A friend recommended your service",
    "what_product_are_you_interested_in": "AI customer support chatbot",
    "describe_your_current_problem": "Our customer support team receives many repeated questions every day. Response time is becoming a problem.",
    "how_are_you_solving_this_problem_now": "We have a team of support agents answering manually",
    "what_is_your_main_goal": "Reduce workload and provide faster answers to customers",
    "do_you_have_budget_for_this_solution": "Yes, we are actively looking for a solution",
    "estimated_budget": "Around 10000-20000 birr",
    "who_will_make_the_final_decision": "I am the CEO",
    "when_are_you_planning_to_start": "Within the next 3 months",
    "have_you_used_similar_products_before": "We tested some basic chatbot tools before",
    "additional_comments": "Can we schedule a product demonstration next week?"
  }
]